
services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "5002:5002"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  web:
    build: .
    command: >
      gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker
      -w 2 -b 0.0.0.0:5000 chat:application
    #volumes:
    #  - ./:/app
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    expose:
      - "5000"

  redis:
    image: redis:alpine
    restart: always
